name: IM-Core v2 QA

on:
  pull_request:
    paths:
      - 'src/core/im-core-v2/**'
      - 'scripts/imcore-v2/**'
      - 'tests/**'
      - 'vitest.config.ts'
      - 'package.json'
  workflow_dispatch: {}

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint -- --max-warnings=2

      - name: Unit tests
        run: npm run test:unit

      - name: Weight balance summary
        run: node --loader tsx ./scripts/imcore-v2/testWeightBalance.ts



